name: Package Publish

on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag version
      id: get_tag_version
      run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Download plugin file
      run: curl -L https://github.com/dprint/dprint-plugin-yapf/releases/download/${{ steps.get_tag_version.outputs.TAG_VERSION }}/yapf.exe-plugin --output yapf.exe-plugin

      # PLUGIN PUBLISH
    - name: Checkout plugins repo
      uses: actions/checkout@v2
      with:
        repository: dprint/plugins
        token: ${{ secrets.CI_REPO_PAT }} # github.token is scoped to current repo, so use this to push to other repo
        path: dprint-plugins
    - name: Plugin publish
      run: |
          cd dprint-plugins
          mv ../yapf.exe-plugin yapf-${{ steps.get_tag_version.outputs.TAG_VERSION }}.exe-plugin
          git add .
          git config user.name "David Sherret"
          git config user.email "dsherret@users.noreply.github.com"
          git commit -m "dprint-plugin-yapf ${{ steps.get_tag_version.outputs.TAG_VERSION }}"
          git push origin master
